<a href="https://colab.research.google.com/github/mahendrasiingh/Python_Libraries/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([[10,20,30,40],[10,20,30,40],[10,20,30,40,]])
print(arr)
print(type(arr))


[[10 20 30 40]
 [10 20 30 40]
 [10 20 30 40]]
<class 'numpy.ndarray'>


In [ ]:
# SLICING IN NUMPY ARRAYS
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0:2,0:2])


[[10 20]
 [50 60]]


In [ ]:
# ATTRIBUTES OF ARRAYS
arr = np.array([[10,20,30,40],[10,20,30,40],[10,20,30,40,]])
print(np.ndim(arr))
print(np.shape(arr))
print(np.size(arr))
print(arr.dtype)


2
(3, 4)
12
int64


In [ ]:
# INSPECTING AN ARRAY
arr = np.array([[10,20,30,40],[10,20,30,40],[10,20,30,40,]])
print(arr.shape)
print(len(arr))
print(np.size(arr))
print(arr.astype(float))
print(arr.astype(str))


(3, 4)
3
12
[[10. 20. 30. 40.]
 [10. 20. 30. 40.]
 [10. 20. 30. 40.]]
[['10' '20' '30' '40']
 ['10' '20' '30' '40']
 ['10' '20' '30' '40']]


In [ ]:
# MATHEMATICAL OPERATIONS AND FUNCTIONS ON ARRAYS

arr1 = np.array([10,20,30,40])
arr2 = np.array([50,60,70,80])

print (arr1+arr2) # normal addition
print(np.add(arr1,arr2)) # using np addition

print(arr1-arr2) # normal subtraction
print(np.subtract(arr1,arr2)) # using np subtraction

print(arr1*arr2) # normal multiplication
print(np.multiply(arr1,arr2)) # using np multiplication

print(arr1/arr2) # normal division
print(np.divide(arr1,arr2)) # using np division


arr3 = np.array([1,2,3,4])
arr4 = np.array([4,3,2,1])
arr5 = np.array([9,16,4,25])

print(np.power(arr3,arr4)) # using np power

print(np.sqrt(arr5)) # using np sqrt




[ 60  80 100 120]
[ 60  80 100 120]
[-40 -40 -40 -40]
[-40 -40 -40 -40]
[ 500 1200 2100 3200]
[ 500 1200 2100 3200]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]
[1 8 9 4]
[3. 4. 2. 5.]


In [ ]:
# COMBINING AND SPLITTING ARRAYS

arr1 = np.array([[10,20,30,40],[1,2,3,4]])
arr2 = np.array([[50,60,70,80],[4,5,6,7]])

arr = np.concatenate((arr1,arr2))
print(arr)

print(np.concatenate((arr1,arr2),axis=1))


print(np.hstack((arr1,arr2))) # horizontal concatenation


print(np.vstack((arr1,arr2))) # vertical concatenation


# SPLIT

arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(np.array_split(arr,2))




[[10 20 30 40]
 [ 1  2  3  4]
 [50 60 70 80]
 [ 4  5  6  7]]
[[10 20 30 40 50 60 70 80]
 [ 1  2  3  4  4  5  6  7]]
[[10 20 30 40 50 60 70 80]
 [ 1  2  3  4  4  5  6  7]]
[[10 20 30 40]
 [ 1  2  3  4]
 [50 60 70 80]
 [ 4  5  6  7]]
[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]


In [ ]:
# ADDING AND REMOVING ELEMENTS IN THE ARRAYS

arr = np.array([10,20,30,40])
print(np.append(arr,[50,60,70])) # append

print(np.insert(arr,2,50)) # insert
print(np.insert(arr,1,[50,60])) # insert

print(np.delete(arr,2)) # delete



[10 20 30 40 50 60 70]
[10 20 50 30 40]
[10 50 60 20 30 40]
[10 20 40]


In [ ]:
# SEARCH , SORT AND FILTER ARRAYS

# SORT

arr = np.array([20,60,4,6,0,7,34,89,1,4,5,])
print(np.sort(arr))

# SEARCH
arr = np.array([20,60,4,6,0,7,5,34,89,1,4,50])
search = np.where(arr % 2 == 0)
print(search)

# SEARCHSORTED
arr = np.array([1,2,3,4,5])
searchsorted = np.searchsorted(arr,3)
print(searchsorted)

# FILTER
arr = np.array([1,2,3,4,5])
filterarray = [True,False,True,False,True]
newarr = arr[filterarray]
print(newarr)


filterarray = arr>2
print(arr[filterarray])


[ 0  1  4  4  5  6  7 20 34 60 89]
(array([ 0,  1,  2,  3,  4,  7, 10, 11]),)
2
[1 3 5]
[3 4 5]


In [ ]:
# AGGREGATING FUNCTIONS IN NUMPY
arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.size(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

15
3.0
1
5
5
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [ ]:
# STATISTICAL FUNCTIONS
import statistics as stats
data = [100,280,600,500,600,940,350,400]
arr = np.array(data)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

471.25
450.0
236.6134770041639
55985.9375
